[project]
name = "lightning-practice"
version = "0.1.0"
description = "Lightning Practice solution for ML-instruments course"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lightning>=2.5.0.post0",
    "pandas>=2.2.3",
    "torchvision>=0.21.0",
]
